name: Deploy Frontend

on:
  push:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npx eslint . --ext .js,.jsx
      - name: Run Tests
        run: npm test
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          start: npm run dev