name: Deploy Frontend

on:
  push:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npx eslint . --ext .js,.jsx
      # - name: Run Tests
      #   run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          build: npm run build
          start: npm start